version: "3.5"

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
      
  nginx:
    container_name: nginx
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    expose: 
      - "9000"


volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /${USER}/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /${USER}/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge